spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/inventory-service
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        # type: TRACE
