eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

spring:
  application:
    name: discovery-server
  security:
    user:
      name: eureka
      password: password
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8761
