spring:
  data:
    mongodb:
      uri: mongodb+srv://necl0usr2:necl0usr2@nodeexpresscluster0.rbtfu.mongodb.net/?retryWrites=true&w=majority
      database: springboot

#three hyphen/dash '---'  start a new document
#---
#three hyphen/dash ---  start a new document