spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://user:pass@cluster.mongodb.net/?retryWrites=true&w=majority
      database: dbname
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost

#three hyphen/dash '---'  start a new document
#---
#three hyphen/dash ---  start a new document
