spring:
  data:
    mongodb:
      uri: mongodb+srv://user:pass@cluster.mongodb.net/?retryWrites=true&w=majority
      database: databasename

#three hyphen/dash '---'  start a new document
#---
#three hyphen/dash ---  start a new document
